### ISSUE TITLE
Website is down.

### ISSUE THREAD

**Issue by vignesh070801** [Haydzyo/Fortnite-KD-Tracker#1]
The K/D site is down, looks like the rental period was over..

**Comment by HaydenBruin** [comment]
This project is no longer live :), updated readme!

**Comment by AugustusFaren** [comment]
So, I came through your typing test repo which was a .js . I just wondered
if I could do the same with C++ (because I have started learning it but not
Java).

Thanks in advance!

**Comment by HaydenBruin** [comment]
Absolutely, go for it :)
